# structure of agent reply

In [29]:
from pydantic import BaseModel
from typing import List

class Task(BaseModel):
    id: int
    name: str
    description: str
    agent_type: str    
    url: str

In [30]:
class TaskPlan(BaseModel):
    user_requirement: str
    tasks: List[Task]

## API keys

In [31]:
from dotenv import load_dotenv
import os

load_dotenv(override=True)

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

In [32]:
from google import genai

gemini_client = genai.Client(
    api_key=GOOGLE_API_KEY
)

print("Gemini client created")

Gemini client created

In [5]:
user_requirement = """
Find me the best laptop under ₹80,000
for programming, gaming and college use.
"""

In [7]:
orchestrator_prompt = f"""
You are the Orchestrator of a shopping research system.

Your job is to understand the user's requirement
and break it into research tasks.

You are NOT doing the research.

For each task determine:

- task id
- task name
- what the task should accomplish
- which type of agent should perform it

Available agent types:

browser
llm
logic

Use browser when information must be collected from websites.
Use llm for reasoning, summarization or analysis.
Use logic for deterministic calculations.

User requirement:

{user_requirement}
"""

## Orchestrator generator

In [8]:
response = gemini_client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents=orchestrator_prompt,
    config={
        "response_mime_type": "application/json",
        "response_schema": TaskPlan.model_json_schema(),
    },
)

In [9]:
print(response.text)

{
  "user_requirement": "Find me the best laptop under ₹80,000 for programming, gaming and college use.",
  "tasks": [
    {
      "id": 1,
      "name": "Search Laptops",
      "description": "Search e-commerce websites and tech retail stores for laptops priced under ₹80,000 suitable for programming, gaming, and college students.",
      "agent_type": "browser",
      "url": "https://www.amazon.in"
    },
    {
      "id": 2,
      "name": "Extract Laptop Specs and Prices",
      "description": "Extract key specifications such as CPU, GPU, RAM, storage, battery life, and exact pricing for the shortlisted laptops from search results.",
      "agent_type": "browser",
      "url": "https://www.flipkart.com"
    },
    {
      "id": 3,
      "name": "Analyze and Compare Laptops",
      "description": "Analyze the gathered specifications against the requirements for programming performance, gaming capability, and college portability to rank the top choices.",
      "agent_type": "llm",
      "url": ""
    },
    {
      "id": 4,
      "name": "Calculate Value Scores",
      "description": "Perform deterministic calculations to score the laptops based on price-to-performance ratio, battery capacity, and hardware specifications.",
      "agent_type": "logic",
      "url": ""
    }
  ]
}

## convert to python objs, not json
## also maintains the TaskPlan Schema

In [10]:
task_plan = TaskPlan.model_validate_json(response.text)

In [11]:
print(task_plan)

user_requirement='Find me the best laptop under ₹80,000 for programming, gaming and college use.' tasks=[Task(id=1, name='Search Laptops', description='Search e-commerce websites and tech retail stores for laptops priced under ₹80,000 suitable for programming, gaming, and college students.', agent_type='browser', url='https://www.amazon.in'), Task(id=2, name='Extract Laptop Specs and Prices', description='Extract key specifications such as CPU, GPU, RAM, storage, battery life, and exact pricing for the shortlisted laptops from search results.', agent_type='browser', url='https://www.flipkart.com'), Task(id=3, name='Analyze and Compare Laptops', description='Analyze the gathered specifications against the requirements for programming performance, gaming capability, and college portability to rank the top choices.', agent_type='llm', url=''), Task(id=4, name='Calculate Value Scores', description='Perform deterministic calculations to score the laptops based on price-to-performance ratio, battery capacity, and hardware specifications.', agent_type='logic', url='')]

In [12]:
import pprint
# type(task_plan)
pprint.pprint(task_plan)

TaskPlan(user_requirement='Find me the best laptop under ₹80,000 for programming, gaming and college use.', tasks=[Task(id=1, name='Search Laptops', description='Search e-commerce websites and tech retail stores for laptops priced under ₹80,000 suitable for programming, gaming, and college students.', agent_type='browser', url='https://www.amazon.in'), Task(id=2, name='Extract Laptop Specs and Prices', description='Extract key specifications such as CPU, GPU, RAM, storage, battery life, and exact pricing for the shortlisted laptops from search results.', agent_type='browser', url='https://www.flipkart.com'), Task(id=3, name='Analyze and Compare Laptops', description='Analyze the gathered specifications against the requirements for programming performance, gaming capability, and college portability to rank the top choices.', agent_type='llm', url=''), Task(id=4, name='Calculate Value Scores', description='Perform deterministic calculations to score the laptops based on price-to-performance ratio, battery capacity, and hardware specifications.', agent_type='logic', url='')])

In [38]:
for task in task_plan.tasks:
    print(
        task.id,
        "|",
        task.name,
        "|",
        task.agent_type
    )

1 | Market Search | browser
2 | Feature Analysis | llm
3 | Score Calculation | logic
4 | Final Recommendation | llm

## same thing with OPENAI

In [13]:
from openai import OpenAI

openai_client = OpenAI(
    api_key=OPENAI_API_KEY
)

print("OpenAI client created")

OpenAI client created

In [14]:
response_openai = openai_client.responses.parse(
    model="gpt-4o-mini",
    input=[
        {
            "role": "system",
            "content": """
You are the Orchestrator of a shopping research system.

Your job is to understand a user's requirement
and break it into research tasks.

You are NOT doing the research.

Available agent types:

- browser
- llm
- logic

Use browser for website research.
Use llm for reasoning and summarization.
Use logic for deterministic calculations.
"""
        },
        {
            "role": "user",
            "content": user_requirement
        }
    ],
    text_format=TaskPlan,
)

In [15]:
task_plan_openai = response_openai.output_parsed

In [16]:
print(task_plan_openai)

user_requirement='Find the best laptop under ₹80,000 suitable for programming, gaming, and college use.' tasks=[Task(id=1, name='Research laptops for programming and gaming', description='Look for laptops under ₹80,000 that excel in both programming and gaming performance.', agent_type='browser', url='https://www.flipkart.com/search?q=laptop+under+80000+for+programming+and+gaming'), Task(id=2, name='Summarize laptop features', description='Summarize the key features, specifications, and pros/cons of the top choices identified in the browser research.', agent_type='llm', url=''), Task(id=3, name='Calculate performance metrics', description='Determine the best price-to-performance ratio for the identified laptops, considering CPU, GPU, and RAM.', agent_type='logic', url='')]

In [17]:
print("===== GEMINI =====")

for task in task_plan.tasks:
    print(
        task.id,
        task.name,
        "→",
        task.agent_type
    )

print("\n===== OPENAI =====")

for task in task_plan_openai.tasks:
    print(
        task.id,
        task.name,
        "→",
        task.agent_type
    )

===== GEMINI =====
1 Search Laptops → browser
2 Extract Laptop Specs and Prices → browser
3 Analyze and Compare Laptops → llm
4 Calculate Value Scores → logic

===== OPENAI =====
1 Research laptops for programming and gaming → browser
2 Summarize laptop features → llm
3 Calculate performance metrics → logic

In [33]:
user_requirement = """
Find the best laptop under ₹80,000 for programming,
gaming and college use.
Compare products from Amazon and Flipkart.
"""

## Return the response in `TaskPlan` format.

In [34]:
def create_plan_gemini(user_requirement: str) -> TaskPlan:
    prompt = f"""
You are the Orchestrator of a shopping research system.

Your job is to understand the user's requirement
and break it into research tasks.

You are NOT doing the research.

For each task determine:

- task id
- task name
- what the task should accomplish
- which type of agent should perform it
- URL to visit if it is a browser task

Available agent types:

browser
llm
logic

Use browser when information must be collected from websites.
Use llm for reasoning, summarization or analysis.
Use logic for deterministic calculations.

For browser tasks:
- provide the exact website URL to visit
- create separate tasks when research should be performed on different websites
- make the task description specific about what information needs to be collected

User requirement:

{user_requirement}
"""
    response = gemini_client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_schema": TaskPlan.model_json_schema(),
        },
    )
    return TaskPlan.model_validate_json(response.text)

In [35]:
plan = create_plan_gemini(
    "Find the best laptop under ₹80,000 for programming and gaming."
)

#### input

In [21]:
print(plan.user_requirement)

Find the best laptop under ₹80,000 for programming and gaming.

#### output of Orchestrator

In [36]:
for task in plan.tasks:
    print("ID:", task.id)
    print("NAME:", task.name)
    print("TYPE:", task.agent_type)
    print("URL:", task.url)
    print("DESCRIPTION:", task.description)
    print("-" * 50)

ID: 1
NAME: Search Amazon India for Gaming Laptops
TYPE: browser
URL: https://www.amazon.in/s?k=gaming+laptop+under+80000
DESCRIPTION: Search for laptops under ₹80,000 suitable for programming and gaming, and extract product names, specifications, and prices.
--------------------------------------------------
ID: 2
NAME: Search Flipkart for Gaming Laptops
TYPE: browser
URL: https://www.flipkart.com/search?q=gaming%20laptop%20under%2080000
DESCRIPTION: Search for laptops under ₹80,000 suitable for programming and gaming, and extract product names, specifications, and prices.
--------------------------------------------------
ID: 3
NAME: Analyze and Compare Laptop Specifications
TYPE: llm
URL:
DESCRIPTION: Analyze the collected laptop options from Amazon and Flipkart, evaluating processors, RAM, GPU, and reviews to recommend the best programming and gaming laptop under ₹80,000.
--------------------------------------------------

In [37]:
import subprocess

## fetch only those result where  `agent_type=browser`

In [24]:
import json

browser_task=[]

for task in plan.tasks:
    if task.agent_type == "browser":
        browser_task.append(task.model_dump())
        
browser_task

[{'id': 1,
  'name': 'Search Amazon for gaming laptops',
  'description': 'Search for laptops priced under 80000 INR suitable for programming and gaming. Collect model names, specifications (CPU, GPU, RAM, Storage), and prices.',
  'agent_type': 'browser',
  'url': 'https://www.amazon.in'},
 {'id': 2,
  'name': 'Search Flipkart for gaming laptops',
  'description': 'Search for laptops priced under 80000 INR suitable for programming and gaming. Collect model names, specifications (CPU, GPU, RAM, Storage), and prices.',
  'agent_type': 'browser',
  'url': 'https://www.flipkart.com'}]

that desciption  of finding laptops is sent in to the browser use

### creating the first_browser agent `(Amazon)`

In [30]:
result_amazon = subprocess.run(
    [
        "python",
        "../agents/product_discovery.py",
        browser_task[0]['url'],
        browser_task[0]["description"]
    ],
    capture_output=True,
    text=True,
    encoding="utf-8"
)

In [33]:
print("return code:", result_amazon.returncode)
print("STDOUT:", result_amazon.stdout)
print("STDERR:", result_amazon.stderr)

return code: 0
STDOUT: {
  "products": [
    {
      "name": "ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6\"(39.6 cm), Windows 11 Home, Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop",
      "price": 73490.0,
      "rating": 4.3,
      "specifications": "AMD Ryzen 7, RTX 3050-4GB, 16GB RAM, 512GB SSD, 15.6\" FHD",
      "url": null,
      "source": "Amazon.in"
    },
    {
      "name": "Acer ALG, Intel Core5-210H Processor, NVIDIA GeForceRTX 3050-4GB DDR6, 16GB RAM/ 512GB SSD, FHD 15.6\", 144Hz, Win 11 Home, Titanium Gray, 1.99 KG, AL15G-53, Gaming Laptop",
      "price": 76999.0,
      "rating": 3.0,
      "specifications": "Intel Core 5-210H, NVIDIA GeForce RTX 3050 4GB, 16GB RAM, 512GB SSD, 15.6\" FHD 144Hz",
      "url": null,
      "source": "Amazon.in"
    },
    {
      "name": "MSI Thin 15, Intel 13th Gen. Core i5-13420H, 40CM FHD 144Hz Gaming Laptop(16GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB /Cosmos Gray/1.86Kg), B13UCX-1807IN",
      "price": 79900.0,
      "rating": 4.2,
      "specifications": "Intel 13th Gen Core i5-13420H, NVIDIA GeForce RTX 2050 4GB, 16GB RAM, 512GB SSD, 40CM FHD 144Hz",
      "url": null,
      "source": "Amazon.in"
    },
    {
      "name": "MSI Thin 15, Intel 12th Gen. Core i5-12450H, 40CM FHD 144Hz Gaming Laptop(8GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB/Cosmos Gray/1.86Kg), B12UCX-1696IN",
      "price": 78999.0,
      "rating": 4.4,
      "specifications": "Intel 12th Gen Core i5-12450H, NVIDIA GeForce RTX 2050 4GB, 8GB RAM, 512GB SSD, 40CM FHD 144Hz",
      "url": null,
      "source": "Amazon.in"
    }
  ]
}

STDERR: INFO     [service] Using anonymized telemetry, see https://docs.browser-use.com/development/monitoring/telemetry.
INFO     [Agent] 🔗 Found URL in task: https://www.amazon.in, adding as initial action...
INFO     [Agent] 🎯 Task:
    Visit this website:

    https://www.amazon.in

    Search for laptops priced under 80000 INR suitable for programming and gaming. Collect model names, specifications (CPU, GPU, RAM, Storage), and prices.

    Find candidate products that match the user's requirement.
    Return the requested product information in the required structured format.

Expected output format: ProductDiscoveryResult
{
  "$defs": {
    "Product": {
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "price": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Price"
        },
        "rating": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rating"
        },
        "specifications": {
          "title": "Specifications",
          "type": "string"
        },
        "url": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Url"
        },
        "source": {
          "title": "Source",
          "type": "string"
        }
      },
      "required": [
        "name",
        "specifications",
        "source"
      ],
      "title": "Product",
      "type": "object"
    }
  },
  "properties": {
    "products": {
      "items": {
        "$ref": "#/$defs/Product"
      },
      "title": "Products",
      "type": "array"
    }
  },
  "required": [
    "products"
  ],
  "title": "ProductDiscoveryResult",
  "type": "object"
}
INFO     [Agent] 📦 Newer version available: 0.13.8 (current: 0.13.7). Upgrade with: uv add browser-use==0.13.8
INFO     [Agent] Starting a browser-use agent with version 0.13.7, with provider=google and model=gemini-3.5-flash-lite
INFO     [Agent]   ▶️   navigate: url: https://www.amazon.in, new_tab: False
WARNING  [BrowserSession] ⚠️ Empty DOM detected after navigation to https://www.amazon.in, waiting 3s and rechecking...
INFO     [tools] 🔗 Navigated to https://www.amazon.in
INFO     [Agent]

INFO     [Agent] 📍 Step 1:
INFO     [Agent]   👍 Eval: Successfully loaded Amazon.in homepage.
INFO     [Agent]   🧠 Memory: Navigated to Amazon.in. Ready to search for laptops under 80000 INR suitable for programming and gaming.
INFO     [Agent]   🎯 Next goal: Search for programming and gaming laptops under 80000 INR.
INFO     [Agent]   ▶️  [1/2] input: index: 778, text: gaming programming laptop under 80000, clear: True
INFO     [BrowserSession] ⌨️ Typed "gaming programming laptop under 80000" into element with index 778
INFO     [Agent]   ▶️  [2/2] click: index: 790
INFO     [tools] 🖱️ Clicked input type=submit id=nav-search-submit-bu
INFO     [Agent] 📋 Plan updated with 3 steps
INFO     [Agent]

INFO     [Agent] 📍 Step 2:
INFO     [Agent]   ❔ Eval: Searched for programming and gaming laptops, but the page content is not yet visible.
INFO     [Agent]   🧠 Memory: Performed search on Amazon.in. Waiting for results to load or scrolling to reveal products.
INFO     [Agent]   🎯 Next goal: Scroll down to check if search results are loaded below the fold.
INFO     [Agent]   ▶️   scroll: down: True, pages: 1.0, index: None
INFO     [tools] 🔍 Scrolled down 667px
INFO     [Agent] 📋 Plan updated with 3 steps
INFO     [Agent]

INFO     [Agent] 📍 Step 3:
INFO     [Agent]   👍 Eval: Successfully performed search and scrolled to view products on Amazon.in. Verdict: Success
INFO     [Agent]   🧠 Memory: Collected candidate laptops from Amazon search results under 80000 INR suitable for programming and gaming, including ASUS TUF A15, Acer ALG, MSI Thin 15 models.
INFO     [Agent]   🎯 Next goal: Complete the task by calling done with the structured product discovery results.
INFO     [Agent]   ▶️   done: data: {'products': [{'name': 'ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm), Windows 11 Home, Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop', 'price': 73490.0, 'rating': 4.3, 'specifications': 'AMD Ryzen 7, RTX 3050-4GB, 16GB RAM, 512GB SSD, 15.6" FHD', 'url': None, 'source': 'Amazon.in'}, {'name': 'Acer ALG, Intel Core5-210H Processor, NVIDIA GeForceRTX 3050-4GB DDR6, 16GB RAM/ 512GB SSD, FHD 15.6", 144Hz, Win 11 Home, Titanium Gray, 1.99 KG, AL15G-53, Gaming Laptop', 'price': 76999.0, 'rating': 3.0, 'specifications': 'Intel Core 5-210H, NVIDIA GeForce RTX 3050 4GB, 16GB RAM, 512GB SSD, 15.6" FHD 144Hz', 'url': None, 'source': 'Amazon.in'}, {'name': 'MSI Thin 15, Intel 13th Gen. Core i5-13420H, 40CM FHD 144Hz Gaming Laptop(16GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB /Cosmos Gray/1.86Kg), B13UCX-1807IN', 'price': 79900.0, 'rating': 4.2, 'specifications': 'Intel 13th Gen Core i5-13420H, NVIDIA GeForce RTX 2050 4GB, 16GB RAM, 512GB SSD, 40CM FHD 144Hz', 'url': None, 'source': 'Amazon.in'}, {'name': 'MSI Thin 15, Intel 12th Gen. Core i5-12450H, 40CM FHD 144Hz Gaming Laptop(8GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB/Cosmos Gray/1.86Kg), B12UCX-1696IN', 'price': 78999.0, 'rating': 4.4, 'specifications': 'Intel 12th Gen Core i5-12450H, NVIDIA GeForce RTX 2050 4GB, 8GB RAM, 512GB SSD, 40CM FHD 144Hz', 'url': None, 'source': 'Amazon.in'}]}, files_to_display: []
INFO     [Agent] 📋 Plan updated with 3 steps
INFO     [Agent]
📄  Final Result:
{"products": [{"name": "ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6\"(39.6 cm), Windows 11 Home, Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop", "price": 73490.0, "rating": 4.3, "specifications": "AMD Ryzen 7, RTX 3050-4GB, 16GB RAM, 512GB SSD, 15.6\" FHD", "url": null, "source": "Amazon.in"}, {"name": "Acer ALG, Intel Core5-210H Processor, NVIDIA GeForceRTX 3050-4GB DDR6, 16GB RAM/ 512GB SSD, FHD 15.6\", 144Hz, Win 11 Home, Titanium Gray, 1.99 KG, AL15G-53, Gaming Laptop", "price": 76999.0, "rating": 3.0, "specifications": "Intel Core 5-210H, NVIDIA GeForce RTX 3050 4GB, 16GB RAM, 512GB SSD, 15.6\" FHD 144Hz", "url": null, "source": "Amazon.in"}, {"name": "MSI Thin 15, Intel 13th Gen. Core i5-13420H, 40CM FHD 144Hz Gaming Laptop(16GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB /Cosmos Gray/1.86Kg), B13UCX-1807IN", "price": 79900.0, "rating": 4.2, "specifications": "Intel 13th Gen Core i5-13420H, NVIDIA GeForce RTX 2050 4GB, 16GB RAM, 512GB SSD, 40CM FHD 144Hz", "url": null, "source": "Amazon.in"}, {"name": "MSI Thin 15, Intel 12th Gen. Core i5-12450H, 40CM FHD 144Hz Gaming Laptop(8GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB/Cosmos Gray/1.86Kg), B12UCX-1696IN", "price": 78999.0, "rating": 4.4, "specifications": "Intel 12th Gen Core i5-12450H, NVIDIA GeForce RTX 2050 4GB, 8GB RAM, 512GB SSD, 40CM FHD 144Hz", "url": null, "source": "Amazon.in"}]}


INFO     [Agent] ✅ Task completed successfully
INFO     [BrowserSession] 📢 on_BrowserStopEvent - Calling reset() (force=True, keep_alive=None)
INFO     [BrowserSession] [SessionManager] Cleared all owned data (targets, sessions, mappings)
INFO     [BrowserSession] ✅ Browser session reset complete
INFO     [BrowserSession] ✅ Browser session reset complete
INFO     [BrowserSession] ✅ Browser session reset complete
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002162371BCE0>
Traceback (most recent call last):
  File "c:\Users\DebayonMallik\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "c:\Users\DebayonMallik\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DebayonMallik\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002162371BCE0>
Traceback (most recent call last):
  File "c:\Users\DebayonMallik\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "c:\Users\DebayonMallik\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DebayonMallik\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

now convert it to dict

In [32]:
amazon_products=json.loads(result_amazon.stdout)["products"]
print(amazon_products)

[{'name': 'ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm), Windows 11 Home, Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop', 'price': 73490.0, 'rating': 4.3, 'specifications': 'AMD Ryzen 7, RTX 3050-4GB, 16GB RAM, 512GB SSD, 15.6" FHD', 'url': None, 'source': 'Amazon.in'}, {'name': 'Acer ALG, Intel Core5-210H Processor, NVIDIA GeForceRTX 3050-4GB DDR6, 16GB RAM/ 512GB SSD, FHD 15.6", 144Hz, Win 11 Home, Titanium Gray, 1.99 KG, AL15G-53, Gaming Laptop', 'price': 76999.0, 'rating': 3.0, 'specifications': 'Intel Core 5-210H, NVIDIA GeForce RTX 3050 4GB, 16GB RAM, 512GB SSD, 15.6" FHD 144Hz', 'url': None, 'source': 'Amazon.in'}, {'name': 'MSI Thin 15, Intel 13th Gen. Core i5-13420H, 40CM FHD 144Hz Gaming Laptop(16GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB /Cosmos Gray/1.86Kg), B13UCX-1807IN', 'price': 79900.0, 'rating': 4.2, 'specifications': 'Intel 13th Gen Core i5-13420H, NVIDIA GeForce RTX 2050 4GB, 16GB RAM, 512GB SSD, 40CM FHD 144Hz', 'url': None, 'source': 'Amazon.in'}, {'name': 'MSI Thin 15, Intel 12th Gen. Core i5-12450H, 40CM FHD 144Hz Gaming Laptop(8GB/512GB NVMe SSD/Windows 11 Home/NVIDIA GeForce RTX 2050,GDDR6 4GB/Cosmos Gray/1.86Kg), B12UCX-1696IN', 'price': 78999.0, 'rating': 4.4, 'specifications': 'Intel 12th Gen Core i5-12450H, NVIDIA GeForce RTX 2050 4GB, 8GB RAM, 512GB SSD, 40CM FHD 144Hz', 'url': None, 'source': 'Amazon.in'}]

### creating the second_browser agent `(Flipkart)`

In [34]:
result_flipkart = subprocess.run(
    [
        "python",
        "../agents/product_discovery.py",
        browser_task[1]['url'],
        browser_task[1]["description"]
    ],
    capture_output=True,
    text=True,
    encoding="utf-8"
)

In [35]:
flipkart_products=json.loads(result_flipkart.stdout)["products"]
print(flipkart_products)

[{'name': 'Acer Aspire 7 (i5 14th Gen) Intel Core 5 210H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA', 'price': 75990.0, 'rating': 4.3, 'specifications': 'Intel Core 5 Processor, 16 GB DDR4 RAM, 512 GB SSD, 6 GB Graphics (NVIDIA), Windows 11 Home', 'url': 'https://www.flipkart.com/search?q=gaming%20laptop%20under%2080000', 'source': 'Flipkart'}, {'name': 'Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA', 'price': 79990.0, 'rating': 3.9, 'specifications': 'Intel Core 7 Processor, 16 GB DDR4 RAM, 512 GB SSD, 6 GB Graphics (NVIDIA), Windows 11 Home', 'url': 'https://www.flipkart.com/search?q=gaming%20laptop%20under%2080000', 'source': 'Flipkart'}, {'name': 'MSI Thin 15 Intel Core i7 13th Gen 13620H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce', 'price': 79990.0, 'rating': 4.5, 'specifications': 'Intel Core i7 Processor (13th Gen), 16 GB DDR4 RAM, 512 GB SSD, 4 GB Graphics (NVIDIA), Windows 11 Home', 'url': 'https://www.flipkart.com/search?q=gaming%20laptop%20under%2080000', 'source': 'Flipkart'}, {'name': 'HP Victus Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce', 'price': 76888.0, 'rating': 4.2, 'specifications': 'Intel Core i5 Processor (13th Gen), 16 GB DDR4 RAM, 512 GB SSD, 4 GB Graphics (NVIDIA), Windows 11 Home', 'url': 'https://www.flipkart.com/search?q=gaming%20laptop%20under%2080000', 'source': 'Flipkart'}, {'name': 'ASUS TUF Gaming F16 (2025) with MSO 2024+M365 Basic (i5 14th Gen) Intel Core 5 - (16 GB/512 GB SSD/Win', 'price': 79990.0, 'rating': 4.6, 'specifications': 'Intel Core 5 Processor, 16 GB DDR5 RAM, 512 GB SSD, Windows 11 Home', 'url': 'https://www.flipkart.com/search?q=gaming%20laptop%20under%2080000', 'source': 'Flipkart'}]

In [238]:
total_products=amazon_products+flipkart_products
print(total_products)

[{'name': 'ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop', 'price': 70990.0, 'rating': 4.3, 'specifications': 'AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM, 512GB SSD, FHD 15.6", Windows 11 Home', 'url': 'https://www.amazon.in/ASUS-FA506NCQ-HN006W-Gaming-Laptop/dp/B0F4J1C1V4/', 'source': 'Amazon India'}, {'name': 'ASUS TUF A15 (2025), Smartchoice, AMD Ryzen 7 7445HS, Gaming Laptop, RTX 3050-4GB, 75W TGP, 16GB RAM (Upgradeable Upto 64GB) 1TB SSD, FHD, 15.6", 144Hz, M365 Basic(1Y), Office 2024, Black, 2.3 Kg, FA506NCG-HN251WS', 'price': 77990.0, 'rating': 4.3, 'specifications': 'AMD Ryzen 7 7445HS, RTX 3050-4GB, 16GB RAM, 1TB SSD, FHD 15.6", 144Hz, Windows 11', 'url': 'https://www.amazon.in/ASUS-FA506NCG-HN251WS-Gaming-Laptop/dp/B0F4J1C1V5/', 'source': 'Amazon India'}, {'name': 'Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA...', 'price': 75990.0, 'rating': 3.9, 'specifications': 'Intel Core 7 Processor, 16 GB DDR4 RAM, 64 bit Windows 11 Home Operating System, 512 GB SSD, 39.62 cm (15.6 Inch) Display, 6 GB Graphics NVIDIA', 'url': 'https://www.flipkart.com/search?q=laptop+under+80000+gaming', 'source': 'Flipkart'}, {'name': 'DELL G15 Intel Core i5 13th Gen 13450HX - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA GeFor...', 'price': 79990.0, 'rating': 4.2, 'specifications': 'Intel Core i5 Processor (13th Gen), 16 GB DDR5 RAM, Windows 11 Operating System, 512 GB SSD, 39.62 cm (15.6 Inch) Display, 6 GB Graphics NVIDIA', 'url': 'https://www.flipkart.com/search?q=laptop+under+80000+gaming', 'source': 'Flipkart'}, {'name': 'Acer Aspire 7 (i5 14th Gen) Intel Core 5 210H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA...', 'price': 77990.0, 'rating': 4.3, 'specifications': 'Intel Core 5 Processor, 16 GB DDR4 RAM, 64 bit Windows 11 Home Operating System, 512 GB SSD, 39.62 cm (15.6 Inch) Display, 6 GB Graphics NVIDIA', 'url': 'https://www.flipkart.com/search?q=laptop+under+80000+gaming', 'source': 'Flipkart'}, {'name': 'HP Victus Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeFor...', 'price': 77990.0, 'rating': 4.4, 'specifications': 'Intel Core i5 Processor (13th Gen), 16 GB DDR4 RAM, Windows 11 Home Operating System, 512 GB SSD, 39.62 cm (15.6 Inch) Display, 4 GB Graphics NVIDIA', 'url': 'https://www.flipkart.com/search?q=laptop+under+80000+gaming', 'source': 'Flipkart'}]

### convert that dict to dataframe

In [239]:
import pandas as pd

df = pd.DataFrame(total_products)

df

,name,price,rating,specifications,url,source
0,"ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 1...",70990.0,4.3,"AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM, 512GB...",https://www.amazon.in/ASUS-FA506NCQ-HN006W-Gam...,Amazon India
1,"ASUS TUF A15 (2025), Smartchoice, AMD Ryzen 7 ...",77990.0,4.3,"AMD Ryzen 7 7445HS, RTX 3050-4GB, 16GB RAM, 1T...",https://www.amazon.in/ASUS-FA506NCG-HN251WS-Ga...,Amazon India
2,Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H ...,75990.0,3.9,"Intel Core 7 Processor, 16 GB DDR4 RAM, 64 bit...",https://www.flipkart.com/search?q=laptop+under...,Flipkart
3,DELL G15 Intel Core i5 13th Gen 13450HX - (16 ...,79990.0,4.2,"Intel Core i5 Processor (13th Gen), 16 GB DDR5...",https://www.flipkart.com/search?q=laptop+under...,Flipkart
4,Acer Aspire 7 (i5 14th Gen) Intel Core 5 210H ...,77990.0,4.3,"Intel Core 5 Processor, 16 GB DDR4 RAM, 64 bit...",https://www.flipkart.com/search?q=laptop+under...,Flipkart
5,HP Victus Intel Core i5 13th Gen 13420H - (16 ...,77990.0,4.4,"Intel Core i5 Processor (13th Gen), 16 GB DDR4...",https://www.flipkart.com/search?q=laptop+under...,Flipkart

In [166]:
import json

with open(
    "../outputs/amazon_products.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        products,
        f,
        indent=2,
        ensure_ascii=False
    )

## Enhancing the Product schema

In [ ]:
# from typing import List,Dict

# class Product_gen(BaseModel):
#     name:str
#     price:float|None=None
#     rating:float|None=None
#     brand:str|None=None
#     url:str|None=None
#     source:str|None=None
#     specifications:Dict[str,str]={}

#### better architecture with automatic browser agents

In [38]:
import json

browser_task=[]

for task in plan.tasks:
    if task.agent_type == "browser":
        browser_task.append(task.model_dump())
        
browser_task

[{'id': 1,
  'name': 'Search Amazon India for Gaming Laptops',
  'description': 'Search for laptops under ₹80,000 suitable for programming and gaming, and extract product names, specifications, and prices.',
  'agent_type': 'browser',
  'url': 'https://www.amazon.in/s?k=gaming+laptop+under+80000'},
 {'id': 2,
  'name': 'Search Flipkart for Gaming Laptops',
  'description': 'Search for laptops under ₹80,000 suitable for programming and gaming, and extract product names, specifications, and prices.',
  'agent_type': 'browser',
  'url': 'https://www.flipkart.com/search?q=gaming%20laptop%20under%2080000'}]

In [39]:
all_products = []

for task in browser_task:

    result = subprocess.run(
        [
            "python",
            "../agents/product_discovery.py",
            task["url"],
            task["description"]
        ],
        capture_output=True,
        text=True,
        encoding="utf-8"
    )

    # parse result
    products=json.loads(result.stdout)["products"]
    # add products
    all_products.extend(products)
print(all_products)

[{'name': 'ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop', 'price': 73490.0, 'rating': 4.3, 'specifications': 'AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6" (39.6 cm), Windows 11 Home, Graphite Black, 2.3 Kg', 'url': 'https://www.amazon.in/ASUS-3050-4GB-Upgradeable-Graphite-FA506NCQ-HN006W/dp/B0GW85JTBN/ref=sr_1_3', 'source': 'Amazon India'}, {'name': "HP Victus, 13th Gen Intel Core i5-13420H, 4GB RTX 2050, 16GB DDR4 (Upgradeable) 512GB SSD, 144Hz, IPS, 300 nits, FHD, 15.6''/39.6cm, Win11, M365* Office24, Mica Silver, 2.3kg, fa2703tx Gaming Laptop", 'price': 72990.0, 'rating': 3.8, 'specifications': '13th Gen Intel Core i5-13420H, 4GB RTX 2050, 16GB DDR4 (Upgradeable), 512GB SSD, 144Hz, IPS, 300 nits, FHD, 15.6"/39.6cm, Win11, M365/Office24, Mica Silver, 2.3kg', 'url': 'https://www.amazon.in/HP-i5-13420H-Upgrade-Office24-fa2703tx/dp/B0DV97GJBK/ref=sr_1_4', 'source': 'Amazon India'}, {'name': 'Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA...', 'price': 79990.0, 'rating': 3.9, 'specifications': 'Intel Core 7 Processor, 16 GB DDR4 RAM, 64 bit Windows 11 Home Operating System, 512 GB SSD, 39.62 cm (15.6 Inch) Display, 1 Year Warranty', 'url': None, 'source': 'Flipkart'}, {'name': 'MSI Thin 15 Intel Core i7 13th Gen 13620H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeF...', 'price': 79990.0, 'rating': 4.5, 'specifications': 'Intel Core i7 Processor (13th Gen), 16 GB DDR4 RAM, Windows 11 Operating System, 512 GB SSD, 39.62 cm (15.6 Inch) Display, 2 Year Onsite Warranty', 'url': None, 'source': 'Flipkart'}, {'name': 'HP Victus Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeFor...', 'price': 76888.0, 'rating': 4.2, 'specifications': 'Intel Core i5 Processor (13th Gen), 16 GB DDR4 RAM, Windows 11 Home Operating System, 512 GB SSD, 39.62 cm (15.6 Inch) Display, Windows 11 and Microsoft Office Home & Student Edition 2024, 1 Year Carry-in Warranty', 'url': None, 'source': 'Flipkart'}, {'name': 'ASUS TUF Gaming F16 (2025) with MSO 2024+M365 Basic (i5 14th Gen) Intel Core 5 - (16 GB/512 GB SSD/Win...', 'price': 79990.0, 'rating': 4.6, 'specifications': 'Intel Core 5 Processor, 16 GB DDR5 RAM, Windows 11 Home Operating System, 512 GB SSD, 40.64 cm (16 inch) Display, Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic(1-Year Validity), McAfee 1 year, 1 Year Onsite Warranty', 'url': None, 'source': 'Flipkart'}]

In [38]:
import pandas as pd

df = pd.DataFrame(all_products)

df

,name,price,rating,specifications,url,source
0,"ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 1...",73490.0,4.3,"AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM, 512GB...",https://www.amazon.in/dp/D059BCFE,Amazon.in
1,"HP Victus, 13th Gen Intel Core i5-13420H, 4GB ...",72990.0,3.8,"13th Gen Intel Core i5-13420H, 4GB RTX 2050, 1...",https://www.amazon.in/dp/A47C02FB,Amazon.in
2,Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD ...,54890.0,4.0,"AMD Ryzen 5 7520U, AMD Graphics, 16GB DDR5 RAM...",https://www.amazon.in/dp/AE48C4ED,Amazon.in
3,"Acer ALG, Intel Core5-210H Processor, NVIDIA G...",76999.0,3.0,"Intel Core 5-210H, NVIDIA GeForce RTX 3050 4GB...",https://www.amazon.in/dp/E7427C82,Amazon.in
4,Acer Aspire 7(i5 14th Gen) Intel Core 5 210H -...,71990.0,4.5,"Intel Core 5 Processor, 16 GB DDR4 RAM, 64 bit...",https://www.flipkart.com,Flipkart

In [43]:
print("Total products:", len(all_products))

Total products: 5

In [44]:
names = [product["name"] for product in all_products]

print("Total:", len(names))
print("Unique names:", len(set(names)))

Total: 5
Unique names: 5

# let's begin Engineered Normalization.

In [45]:
import re

def normalize_name(name):
    name = name.lower()

    # remove punctuation
    name = re.sub(r"[^a-z0-9\s]", " ", name)

    # remove extra spaces
    name = re.sub(r"\s+", " ", name).strip()

    return name

In [46]:
test = all_products[0]["name"]

print("Original:")
print(test)

print("\nNormalized:")
print(normalize_name(test))

Original:
ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop

Normalized:
asus tuf a15 amd ryzen 7 170 rtx 3050 4gb 16gb ram upgradeable 512gb ssd fhd 15 6 39 6 cm windows 11 home graphite black 2 3 kg fa506ncq hn006w gaming laptop

### inserted normalized name in each products

In [47]:
for product in all_products:
    product["normalized_name"] = normalize_name(product["name"])

In [48]:
all_products[0]

{'name': 'ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop',
 'price': 73490.0,
 'rating': 4.3,
 'specifications': 'AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM, 512GB SSD, FHD 15.6" Display, Windows 11 Home',
 'url': 'https://www.amazon.in/dp/D059BCFE',
 'source': 'Amazon.in',
 'normalized_name': 'asus tuf a15 amd ryzen 7 170 rtx 3050 4gb 16gb ram upgradeable 512gb ssd fhd 15 6 39 6 cm windows 11 home graphite black 2 3 kg fa506ncq hn006w gaming laptop'}

### Data cleansing, finding same normalized names.
### A certain level of cleansing we are performiing, and after that we will send it to gemini to find duplicate prods.

In [49]:
from collections import Counter

name_counts = Counter(
    product["normalized_name"]
    for product in all_products
)

In [50]:
duplicates = {
    name: count
    for name, count in name_counts.items()
    if count > 1
}

duplicates

{}

In [53]:
def get_candidate_key(name):
    normalized = normalize_name(name)
    words = normalized.split()

    return " ".join(words[:10])

In [54]:
for product in all_products:
    print(
        get_candidate_key(product["name"]),
        "|",
        product["source"]
    )

asus tuf a15 amd ryzen 7 170 rtx 3050 4gb | Amazon.in
hp victus 13th gen intel core i5 13420h 4gb rtx | Amazon.in
lenovo v15 g4 amd ryzen 5 7520u 15 6 inch | Amazon.in
acer alg intel core5 210h processor nvidia geforcertx 3050 4gb | Amazon.in
acer aspire 7 i5 14th gen intel core 5 210h | Flipkart

In [55]:
from collections import defaultdict
groups = defaultdict(list)

for product in all_products:
    key = get_candidate_key(product["name"])
    groups[key].append(product)

In [56]:
for key, products in groups.items():

    print("\nGROUP:", key)

    for product in products:
        print(
            " ",
            product["source"],
            "|",
            product["name"],
            "| ₹",
            product["price"]
        )

GROUP: asus tuf a15 amd ryzen 7 170 rtx 3050 4gb
  Amazon.in | ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop | ₹ 73490.0

GROUP: hp victus 13th gen intel core i5 13420h 4gb rtx
  Amazon.in | HP Victus, 13th Gen Intel Core i5-13420H, 4GB RTX 2050, 16GB DDR4 (Upgradeable) 512GB SSD, 144Hz, IPS, 300 nits, FHD, 15.6''/39.6cm, Win11, M365* Office24, Mica Silver, 2.3kg, fa2703tx Gaming Laptop | ₹ 72990.0

GROUP: lenovo v15 g4 amd ryzen 5 7520u 15 6 inch
  Amazon.in | Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD Laptop, AMD Graphics, 16GB DDR5 5500Mhz Ram, 512GB SSD NVMe, Windows 11, Dolby Audio, Arctic Grey, 1 Year Onsite Brand Warranty | ₹ 54890.0

GROUP: acer alg intel core5 210h processor nvidia geforcertx 3050 4gb
  Amazon.in | Acer ALG, Intel Core5-210H Processor, NVIDIA GeForceRTX 3050-4GB DDR6,16GB RAM/ 512GB SSD, FHD 15.6", 144Hz, Win 11 Home, Titanium Gray, 1.99 KG, AL15G-53, Gaming Laptop | ₹ 76999.0

GROUP: acer aspire 7 i5 14th gen intel core 5 210h
  Flipkart | Acer Aspire 7(i5 14th Gen) Intel Core 5 210H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA ... | ₹ 71990.0

## LLM as a judge for same product

In [57]:
from pydantic import BaseModel


class MatchResult(BaseModel):
    same_product: bool
    confidence: float
    reason: str

In [58]:
def match_products(product1, product2):

    prompt = f"""
You are a product matching system.

Determine whether the following two listings
refer to the SAME physical product.

Product 1:
Name: {product1["name"]}
Specifications: {product1.get("specifications")}
Source: {product1["source"]}

Product 2:
Name: {product2["name"]}
Specifications: {product2.get("specifications")}
Source: {product2["source"]}

Important:
- Ignore differences in seller/source.
- Ignore price differences.
- Ignore minor formatting differences.
- Look for model numbers, product identifiers,
  specifications and other identifying information.
- Do not assume two products are the same just
  because their names are similar.

Return:
- same_product: true or false
- confidence: number between 0 and 1
- reason: short explanation
"""
    
    response = gemini_client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_schema": MatchResult.model_json_schema(),
        },
    )

    return MatchResult.model_validate_json(response.text)

In [59]:
for i, product in enumerate(all_products):
    print(i, product["name"], "|", product["source"])

0 ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop | Amazon.in
1 HP Victus, 13th Gen Intel Core i5-13420H, 4GB RTX 2050, 16GB DDR4 (Upgradeable) 512GB SSD, 144Hz, IPS, 300 nits, FHD, 15.6''/39.6cm, Win11, M365* Office24, Mica Silver, 2.3kg, fa2703tx Gaming Laptop | Amazon.in
2 Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD Laptop, AMD Graphics, 16GB DDR5 5500Mhz Ram, 512GB SSD NVMe, Windows 11, Dolby Audio, Arctic Grey, 1 Year Onsite Brand Warranty | Amazon.in
3 Acer ALG, Intel Core5-210H Processor, NVIDIA GeForceRTX 3050-4GB DDR6,16GB RAM/ 512GB SSD, FHD 15.6", 144Hz, Win 11 Home, Titanium Gray, 1.99 KG, AL15G-53, Gaming Laptop | Amazon.in
4 Acer Aspire 7(i5 14th Gen) Intel Core 5 210H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA ... | Flipkart

In [60]:
product1 = all_products[0]
product2 = all_products[1]
product1

{'name': 'ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop',
 'price': 73490.0,
 'rating': 4.3,
 'specifications': 'AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM, 512GB SSD, FHD 15.6" Display, Windows 11 Home',
 'url': 'https://www.amazon.in/dp/D059BCFE',
 'source': 'Amazon.in',
 'normalized_name': 'asus tuf a15 amd ryzen 7 170 rtx 3050 4gb 16gb ram upgradeable 512gb ssd fhd 15 6 39 6 cm windows 11 home graphite black 2 3 kg fa506ncq hn006w gaming laptop'}

In [61]:
match_result = match_products(product1, product2)

print(match_result)

same_product=False confidence=1.0 reason='The products are from completely different brands and series: Product 1 is an ASUS TUF A15 with an AMD processor and RTX 3050, while Product 2 is an HP Victus with an Intel processor and RTX 2050.'

## Deduplicate products across sources (LLM-assisted)

Apply `match_products` only *within* each candidate-key group (cheap, since blocking already
narrowed candidates), merge transitively-matched listings with a small union-find, then
collapse each cluster into one canonical product record.

In [62]:
def dedupe_group(products, threshold=0.7):
    """Cluster duplicate listings within a single candidate-key group."""
    n = len(products)

    # 0 or 1 listing: nothing to compare, no LLM call needed.
    if n <= 1:
        return [products] if n == 1 else []

    parent = list(range(n))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(i, j):
        ri, rj = find(i), find(j)
        if ri != rj:
            parent[rj] = ri

    # Only pairs *within* this (already blocked) group are judged by the LLM.
    for i in range(n):
        for j in range(i + 1, n):
            result = match_products(products[i], products[j])
            if result.same_product and result.confidence >= threshold:
                union(i, j)

    clusters = defaultdict(list)
    for i in range(n):
        clusters[find(i)].append(products[i])

    return list(clusters.values())

In [40]:
def merge_cluster(cluster):
    """Collapse a cluster of duplicate listings into one canonical product."""

    # Prefer the listing with the most detailed specs as the canonical record.
    canonical = max(cluster, key=lambda p: len(p.get("specifications") or ""))

    listings = [
        {
            "source": p.get("source"),
            "price": p.get("price"),
            "rating": p.get("rating"),
            "url": p.get("url"),
        }
        for p in cluster
    ]

    prices = [l["price"] for l in listings if l["price"] is not None]

    return {
        "name": canonical["name"],
        "normalized_name": canonical.get("normalized_name"),
        "specifications": canonical.get("specifications"),
        "listings": listings,
        "sources": [l["source"] for l in listings],
        "min_price": min(prices) if prices else None,
    }

In [63]:
unique_products = []

for key, group_products in groups.items():
    for cluster in dedupe_group(group_products):
        unique_products.append(merge_cluster(cluster))

print("Total listings:", len(all_products))
print("Unique products:", len(unique_products))

Total listings: 5
Unique products: 5

In [64]:
df_unique = pd.DataFrame(unique_products)
df_unique

,name,normalized_name,specifications,listings,sources,min_price
0,"ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 1...",asus tuf a15 amd ryzen 7 170 rtx 3050 4gb 16gb...,"AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM, 512GB...","[{'source': 'Amazon.in', 'price': 73490.0, 'ra...",[Amazon.in],73490.0
1,"HP Victus, 13th Gen Intel Core i5-13420H, 4GB ...",hp victus 13th gen intel core i5 13420h 4gb rt...,"13th Gen Intel Core i5-13420H, 4GB RTX 2050, 1...","[{'source': 'Amazon.in', 'price': 72990.0, 'ra...",[Amazon.in],72990.0
2,Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD ...,lenovo v15 g4 amd ryzen 5 7520u 15 6 inch fhd ...,"AMD Ryzen 5 7520U, AMD Graphics, 16GB DDR5 RAM...","[{'source': 'Amazon.in', 'price': 54890.0, 'ra...",[Amazon.in],54890.0
3,"Acer ALG, Intel Core5-210H Processor, NVIDIA G...",acer alg intel core5 210h processor nvidia gef...,"Intel Core 5-210H, NVIDIA GeForce RTX 3050 4GB...","[{'source': 'Amazon.in', 'price': 76999.0, 'ra...",[Amazon.in],76999.0
4,Acer Aspire 7(i5 14th Gen) Intel Core 5 210H -...,acer aspire 7 i5 14th gen intel core 5 210h 16...,"Intel Core 5 Processor, 16 GB DDR4 RAM, 64 bit...","[{'source': 'Flipkart', 'price': 71990.0, 'rat...",[Flipkart],71990.0

In [65]:
with open(
    "../outputs/unique_products.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        unique_products,
        f,
        indent=2,
        ensure_ascii=False
    )

print("Saved", len(unique_products), "unique products to ../outputs/unique_products.json")

Saved 5 unique products to ../outputs/unique_products.json

# Research Agent

In [66]:
class ProductResearch(BaseModel):
    product_name: str
    specifications: dict[str, str]
    source_urls: list[str]

In [67]:
product = unique_products[0]

print("PRODUCT:")
print(product["name"])

print("\nLISTINGS:")
for listing in product["listings"]:
    print(listing)

PRODUCT:
ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop

LISTINGS:
{'source': 'Amazon.in', 'price': 73490.0, 'rating': 4.3, 'url': 'https://www.amazon.in/dp/D059BCFE'}

In [68]:
product = unique_products[0]

print(product["name"])

ASUS TUF A15, AMD Ryzen 7 170, RTX 3050-4GB, 16GB RAM (Upgradeable), 512GB SSD, FHD, 15.6"(39.6 cm),Windows 11 Home,Graphite Black, 2.3 Kg, FA506NCQ-HN006W, Gaming Laptop

In [69]:
for listing in product["listings"]:
    print(listing["source"])
    print(listing["url"])
    print()

Amazon.in
https://www.amazon.in/dp/D059BCFE

In [70]:
listing = product["listings"][0]

In [74]:
url = "https://www.amazon.in"
product_name = product["name"]
url

'https://www.amazon.in'

# YOUTUBE RESEARCH

In [4]:
from googleapiclient.discovery import build
from dotenv import load_dotenv
import os

load_dotenv(override=True)

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")

youtube = build(
    "youtube", 
    "v3", 
    developerKey=YOUTUBE_API_KEY
    )

### Search for the top 20 results on Youtube, and get their id's

In [22]:
def search_videos(query,max_no_results=20):

    request=youtube.search().list(
        q=query,
        part="snippet",
        type="video",
        maxResults=max_no_results,
        order="relevance"
    )

    response=request.execute()
    
    videos = []
    for item in response["items"]:
        video_meta_data={
        "video_id":item["id"]["videoId"],
        "title":item["snippet"]["title"],
        "thumbnail_url":item["snippet"]["thumbnails"]["default"]["url"],
        "published": item["snippet"]["publishedAt"],
        "description": item["snippet"]["description"],
        "channel":item["snippet"]["channelTitle"]
        }
        videos.append(video_meta_data)


    return videos

In [23]:
search_videos("Sony WH-1000XM5 review")

[{'video_id': 'aWWHU8-5oqU',
  'title': 'Sony WH 1000XM5 Review - Audiophile Perspective | The Best ANC Headphones?',
  'thumbnail_url': 'https://i.ytimg.com/vi/aWWHU8-5oqU/default.jpg',
  'published': '2022-11-06T06:30:00Z',
  'description': "Sony's 2022 iteration of its popular XM series of headphones is the new WH 1000XM5. I've used this for a while now and here's ...",
  'channel': 'Trakin Tech English'},
 {'video_id': '6CsJZxfZsL0',
  'title': 'Sony WH-1000XM5 Review: Two Steps Forward, One Step Back!',
  'thumbnail_url': 'https://i.ytimg.com/vi/6CsJZxfZsL0/default.jpg',
  'published': '2022-05-12T16:01:05Z',
  'description': "Sony's MK5 noise cancelling headphones are still king of the hill, Sony WH1000XM5: https://geni.us/F6x4cC Sony WH1000XM4: ...",
  'channel': 'Marques Brownlee'},
 {'video_id': 'qnEKEI4ZoHo',
  'title': 'Sony WH-1000XM5 Review - Taylor Swift Sounds Good in These',
  'thumbnail_url': 'https://i.ytimg.com/vi/qnEKEI4ZoHo/default.jpg',
  'published': '2022-06-16T22:52:50Z',
  'description': 'Sony wh-1000xm5 headphone sound test and review. In this video, you will see how the Sony wh-1000xm5 headphones sound ...',
  'channel': 'Ryan Kennedy'},
 {'video_id': 'k_fbRCo-yAs',
  'title': 'Spectacular Headphones With Best ANC | Sony WH-1000XM5',
  'thumbnail_url': 'https://i.ytimg.com/vi/k_fbRCo-yAs/default.jpg',
  'published': '2022-11-26T10:42:36Z',
  'description': 'Visit Croma: ⚡SONY WH-1000XM5 Bluetooth Headset with Mic: https://omgrefer.com/SgaL7 ⚡Offer: 10% upto 500 off on ...',
  'channel': "Venom's Tech"},
 {'video_id': 'dEHYA-jACoU',
  'title': 'Sony WH-1000XM5 Headphones Review - 6 Months Later',
  'thumbnail_url': 'https://i.ytimg.com/vi/dEHYA-jACoU/default.jpg',
  'published': '2022-11-21T15:30:15Z',
  'description': 'The Sony WH-1000XM5s are one of the best Bluetooth wireless headphones on the market, but is it a pair everyone should pick ...',
  'channel': '6 Months Later'},
 {'video_id': 'vMi6olkSj7g',
  'title': 'Sony WH-1000XM5 Two-Years Later Review: Still Worth BUYING?',
  'thumbnail_url': 'https://i.ytimg.com/vi/vMi6olkSj7g/default.jpg',
  'published': '2024-07-13T15:00:49Z',
  'description': 'Buy at Amazon: https://soundg.co/qho9e2 The Sony WH-1000XM5 are one of the most popular noise canceling headphones on ...',
  'channel': 'SoundGuys'},
 {'video_id': 'kd1-iS8e7uw',
  'title': 'Sony WH-1000XM5 Review: WORTH IT in 2025?',
  'thumbnail_url': 'https://i.ytimg.com/vi/kd1-iS8e7uw/default.jpg',
  'published': '2025-03-19T21:47:53Z',
  'description': 'Sony WH-1000XM5 (Amazon): https://geni.us/2cqHQp - Read the FULL blog post + EQ Settings: ...',
  'channel': 'RecordingNOW'},
 {'video_id': 'LdIFoJ_aGE8',
  'title': 'Sony XM5 Review | Best of Sony ANC Headphones?',
  'thumbnail_url': 'https://i.ytimg.com/vi/LdIFoJ_aGE8/default.jpg',
  'published': '2022-11-03T04:24:23Z',
  'description': 'Sony WH-1000 XM5 review these are the latest flagship ANC (noise cancelling) headphones from Sony and successor to the ...',
  'channel': 'Geekyranjit'},
 {'video_id': 'UZhn-Q5OhJw',
  'title': 'Sony WH-1000XM5 headphones - 3 months later | Mark Ellis Reviews',
  'thumbnail_url': 'https://i.ytimg.com/vi/UZhn-Q5OhJw/default.jpg',
  'published': '2022-08-12T14:00:15Z',
  'description': "I've been using the Sony WH-1000XM5 noise-cancelling headphones solidly for around three months now. How do they fare after ...",
  'channel': 'Mark Ellis Reviews'},
 {'video_id': 'zolOnpuOHaA',
  'title': 'I&#39;ve been SPOILED! - Sony WH-1000XM5',
  'thumbnail_url': 'https://i.ytimg.com/vi/zolOnpuOHaA/default.jpg',
  'published': '2022-05-12T21:15:42Z',
  'description': "If you're reading this, you probably missed your chance to get a discount on all dbrand products. Use offer code FOURFOOTNINE ...",
  'channel': 'ShortCircuit'},
 {'video_id': 'zPzw6XRpOkI',
  'title': 'Sony WH 1000 XM5 | Headset |  My Review | Malayalam',
  'thumbnail_url': 'https://i.ytimg.com/vi/zPzw6XRpOkI/default.jpg',
  'published': '2024-01-29T06:23:52Z',
  'description': '',
  'channel': 'CallMeShazzam TECH'},
 {'video_id': 'vRc_6PgmM8M',
  'title': 'Sony WH-1000XM5 - 3 Years Later Review',
  'thumbnail_url': 'https://i.ytimg.com/vi/vRc_6PgmM8M/default.jpg',
  'published': '2025-12-23T14:01:41Z',
  'description': 'Buy the Sony WH-1000XM5 on Amazon: https://soundg.co/8snhy2 [Affiliate Disclosure: As an Amazon Associate we earn from ...',
  'channel': 'SoundGuys'},
 {'video_id': 'MBSjoqUFWxk',
  'title': 'Sony WH-1000XM6 and WH-1000XM5 Reviewed &amp; Compared by an AUDIO ENGINEER',
  'thumbnail_url': 'https://i.ytimg.com/vi/MBSjoqUFWxk/default.jpg',
  'published': '2025-05-15T16:00:39Z',
  'description': "The Sony WH-1000XM6 is Sony's latest flagship wireless Bluetooth headset, following the popular Sony WH-1000XM5. In this ...",
  'channel': 'This is Tech Today'},
 {'video_id': 'y5rCUK8KmhQ',
  'title': 'Sony ULT Wear and WH-1000XM5 Reviewed &amp; Compared by an AUDIO ENGINEER',
  'thumbnail_url': 'https://i.ytimg.com/vi/y5rCUK8KmhQ/default.jpg',
  'published': '2024-04-11T16:00:50Z',
  'description': "The Sony ULT Wear is a new pair of wireless Bluetooth headphones by Sony. It doesn't replace the Sony WH-1000XM5 but is a ...",
  'channel': 'This is Tech Today'},
 {'video_id': 'ucaVO3a8aJU',
  'title': 'Sound comparison of Sony WH1000xm5 vs xm6 headphones',
  'thumbnail_url': 'https://i.ytimg.com/vi/ucaVO3a8aJU/default.jpg',
  'published': '2025-06-12T07:33:10Z',
  'description': '',
  'channel': 'TECHKNOW BIZ'},
 {'video_id': '1lUXiZqX_HQ',
  'title': 'Sony WH-1000XM5 Unboxing &amp; First Look - The Best Gets Better🎧🔥🔥🔥',
  'thumbnail_url': 'https://i.ytimg.com/vi/1lUXiZqX_HQ/default.jpg',
  'published': '2022-09-29T09:40:14Z',
  'description': 'Namaskaar Dosto, yeh video hai Sony ke naye premium headphones WH-1000XM5 ke baare mein. Sony aaj tak market leader ...',
  'channel': 'Technical Guruji'},
 {'video_id': '6WTHBCZBt_E',
  'title': 'THE DEFINITIVE Sony WH-1000XM5 Review &amp; Comparison by an AUDIO ENGINEER',
  'thumbnail_url': 'https://i.ytimg.com/vi/6WTHBCZBt_E/default.jpg',
  'published': '2022-05-17T02:30:41Z',
  'description': 'As an Audio Engineer, this is the definitive, in-depth, and experiential review of the Sony WH-1000XM5 and a comparison with the ...',
  'channel': 'This is Tech Today'},
 {'video_id': 'ktQXNjsCEeo',
  'title': 'an HONEST review on the @Sony WH-1000XM5 🎧🤍!',
  'thumbnail_url': 'https://i.ytimg.com/vi/ktQXNjsCEeo/default.jpg',
  'published': '2024-12-03T22:37:05Z',
  'description': "SUBSCRIBE ✧ https://www.youtube.com/channel/UC85YJSmQ6RX9-OcwFuB5oYw?sub_confirmation=1 ✧ LET'S BE FRIENDS ...",
  'channel': 'Cynthia Hau'},
 {'video_id': 'YSLaWs5FzuU',
  'title': 'Sony WH-1000XM5 Review | 18 Months On | Long Term Review',
  'thumbnail_url': 'https://i.ytimg.com/vi/YSLaWs5FzuU/default.jpg',
  'published': '2023-12-28T14:00:22Z',
  'description': 'Sony WH-1000XM5: https://amzn.to/4a7yRDo Beats Studio Pro: https://amzn.to/3TXTKM3 Bose QC45: https://amzn.to/3txXuc9 ...',
  'channel': 'Steven Foster'},
 {'video_id': '9a-3r2llDjI',
  'title': 'Sony WH-1000XM5  (Problems &amp; Best Features after 1 Month Daily Use)',
  'thumbnail_url': 'https://i.ytimg.com/vi/9a-3r2llDjI/default.jpg',
  'published': '2022-06-24T14:30:37Z',
  'description': "SONY WH-1000XM5 https://mikeobrienmedia.com/WH-1000XM5 Follow me on social media! (it's always just @mikeobrienn) ...",
  'channel': "Mike O'Brien"}]

### Fetch some stats of a video eg:-views,likes,total commnets

In [6]:
def get_video_stats(video_id):
    request=youtube.videos().list(
        part="statistics",
        id=video_id
    )
    response=request.execute()
    stats = response["items"][0]["statistics"]
    video_stats={
        "views": int(stats.get("viewCount", 0)),
        "likes": int(stats.get("likeCount", 0)),
        "comment_count": int(stats.get("commentCount", 0))
    }
    return video_stats

In [24]:
get_video_stats("k_fbRCo-yAs")

{'views': 87651, 'likes': 3521, 'comment_count': 300}

### Find top commnets of a single video

In [7]:
def get_top_comments(video_id, max_results=30):
    request = youtube.commentThreads().list(
        part="snippet",
        videoId=video_id,
        order="relevance",   # gets highest-engagement comments first
        maxResults=max_results,
        textFormat="plainText"
    )
    response = request.execute()
    comments = []
    for item in response["items"]:
        top = item["snippet"]["topLevelComment"]["snippet"]
        comments.append({
            "text": top["textDisplay"],
            "likes": top["likeCount"],
            "author": top["authorDisplayName"]
        })
    return comments

In [25]:
get_top_comments("k_fbRCo-yAs")

[{'text': 'We need that kind of mic test in every video going forward',
  'likes': 14,
  'author': '@Ok_Sounds_Good'},
 {'text': '2:35 "jabbaaa tera ghar bar kidar hai" 😂',
  'likes': 3,
  'author': '@devil-d67'},
 {'text': 'Alreay using these from Last 3 months. Best headphone ever used❤. Beast of ANC🔥',
  'likes': 11,
  'author': '@TechEncoders'},
 {'text': '7:37 KR dollar sign. Bhai apna dollar ka fan 🎉',
  'likes': 1,
  'author': '@caabhisheksingh6300'},
 {'text': "I'm watching this while wearing these headphones. The KING of noise cancellation.❤",
  'likes': 12,
  'author': '@benmetalhead'},
 {'text': 'I loving watching tech reviews from Venom\'s Tech. So I thought of watching the review of a product I already own and I am not disappointed. I am a dialysis patient and I spend 4 hours in dialysis thrice a week, there is too much noise in the dialysis center. So whenever there is too much sound, I turn on the noise-cancelling on this headphone and enjoy the peace "me time". Thank you, Sony <3',
  'likes': 4,
  'author': '@peudogamin'},
 {'text': 'Proud to be Indian ❤️', 'likes': 1, 'author': '@kgamerz6992'},
 {'text': 'Your and techno notification at same time but tech is over games',
  'likes': 1,
  'author': '@adgooned'},
 {'text': 'Venom bhai ke struggle ke liye hats off bathroom two wheel indoor outdoor sab jagh ki awaj sunai h doubt sare clear krte h 🔥😂😂',
  'likes': 0,
  'author': '@animetube6769'},
 {'text': '7:05 i am wearing these headphones rn and when that bass came i was amazed 🤯',
  'likes': 1,
  'author': '@sensaixistnc'},
 {'text': 'We are sony lover', 'likes': 1, 'author': '@NumanNasir-cl4oj'},
 {'text': 'Bhai hai ❤', 'likes': 1, 'author': '@anshugiri7960'},
 {'text': 'very badia headphones ha ji black is looking awesome',
  'likes': 0,
  'author': '@navyugsingh6288'},
 {'text': "Bhai 500k pe kuch QnA session etc kro, bohot acche swal hai jaise venom's tech name kha se aaya, future plans etc",
  'likes': 0,
  'author': '@raviundhad1929'},
 {'text': 'Bro best headphone for gaming under 1000 btw love you ❤',
  'likes': 0,
  'author': '@Rohanunfiltered-r7'},
 {'text': 'Wow bro we love and enjoy your videos',
  'likes': 0,
  'author': '@princepanwar1968'},
 {'text': 'Loveyou boss best tech youtuber',
  'likes': 0,
  'author': '@slayer9518'},
 {'text': 'Thumbnail change kr lijiye... Qki thumbnail se pta hi ni chal ra h ki sony ke kisi headphone ki baat ho ri h.. Aise lag ra h jaise ACTIVE NOISE Cancellation ki baat ho rhi h... Suggestion sir ji... But video 🔥🔥🔥🔥👌👌👌👌',
  'likes': 1,
  'author': '@vrijay'},
 {'text': "Nice bro. Bro please unboxing hw8 Max smartwatch it's apple watch series 8 next level copy",
  'likes': 1,
  'author': '@jinnatunnesha7174'},
 {'text': 'you are the best youtuber',
  'likes': 0,
  'author': '@tejathakur1883'},
 {'text': "Please make a video on gaming backpacks for college students.\nIt's a request .",
  'likes': 0,
  'author': '@dakshsharma4775'},
 {'text': 'east and west venom tech is best 🥰🥰',
  'likes': 13,
  'author': '@Kritesh.0'},
 {'text': 'Venom vai vi Mitraz ka fan 🥰', 'likes': 0, 'author': '@debroy02'},
 {'text': 'Bhai Infinix X2 plus laptop ka review kro plzzz.........',
  'likes': 0,
  'author': '@sagarghayal2854'},
 {'text': 'Bhaiya under 5000 ka best tws par video lekar aao plss, priority- sound quality(non-gaming), high battery life with buds.🙃',
  'likes': 0,
  'author': '@adityakumarshaw1598'},
 {'text': 'Bhai best gaming laptop pr ek series bnado .',
  'likes': 0,
  'author': '@its.Nishant.here.'},
 {'text': 'Ubon couple air pod review 👌👌', 'likes': 0, 'author': '@gautam484'},
 {'text': 'First sir love your videos',
  'likes': 0,
  'author': '@jashbhimjiyani7264'},
 {'text': 'Please make video for dual pairing wireless over ear headset under 5000 for music lovers . Please sir',
  'likes': 0,
  'author': '@surajbagul9836'},
 {'text': 'Bhai BOSE ka headphone review Karo',
  'likes': 1,
  'author': '@shubhadeepsutradhar9396'}]

## The `importan` part..is to get the Transcript of a video!!!!

In [8]:
from youtube_transcript_api import YouTubeTranscriptApi

ytt_api = YouTubeTranscriptApi()

def get_transcript(video_id):
    try:
        fetched_transcript = ytt_api.fetch(video_id)
        # fetched_transcript is iterable of snippets with .text, .start, .duration
        return " ".join(snippet.text for snippet in fetched_transcript)
    except Exception as e:
        print(f"Transcript error for {video_id}: {type(e).__name__}: {e}")
        return None

In [28]:
get_transcript("9a-3r2llDjI")

"so it's been one month since sony launched their new flagship headphones to 1000 x mark 5's and when they came out there was a lot of excitement a lot of claims that these are the best of the best the best wireless headphones you can buy but now that it's been a month i want to talk about what it's actually like to use these as i've been using them in many situations on a day-to-day basis from working out to commuting to working in an office to just hanging out and listening to music and all of those i found some things that are not just based on the spec sheet so i want to spend this video talking a little bit more about the nuances of these headphones to help you decide whether or not they're actually the best pair for you to buy so this is sort of like a day in the life i kind of want to break this down into different categories of like when i was using them so what it's like to use them when you're working out what it's like to use them when you're commuting and i want to break it down kind of in that sense so starting off with when you're working i do a lot of working i'm always editing videos and wearing headphones is a critical part of that i'm always listening to music or listening to the videos i'm editing and so obviously audio quality is going to be a big one but before we get too much into the audio quality sometimes when you're working in a space and people are going to come over and talk to you you want to have transparency mode on and so with these transparency mode was pretty decent it's not quite at the level of the airpods max in my opinion meaning it doesn't sound like you have nothing on your ears you can tell everything's a little bit more muted kind of a little bit more robotic regardless it does a decent enough job of picking up on voices and and not always relaying all the small white noises now one of the big positives however is that you can connect to two devices at the same time but the caveat here so personally i like connecting to my phone and to my laptop so i can work and edit and then if i get a phone call just easily switch over but the caveat is you can't use two devices at the same time if you're using one of the higher quality codecs such as ldac now if you want to really prioritize sound quality you can only connect to one device it makes sense of course you can have higher bit rate you can't have multiple you can't have your connection divided another thing is when i'm wearing these for a long time although they're super comfortable they're definitely a lot better in my opinion than the x mark fours from from two years ago but i will say that your ears might get a little bit warm personally i didn't really feel like that was a big issue for me but if you're in a warmer environment it's definitely going to catch up to you now like i said these are comfortable while you're wearing them they're super lightweight it's really like the softest foam ever and the fit and the feel of them really reminds me a lot of the bose headphones and so ever since bose came out with their headphones that look a lot like these like they slide like that and i don't know just very similar design i always loved the bose headphones for comfort it feels like you don't have anything on your head but what bows lacked that these do have is a little bit more grip bows i felt like would fall off my head a little bit more if i was walking around on a phone call whereas these tend to be a lot more secure something i thought was kind of interesting is that they call this vegan leatherette which is a hilarious marketing term for synthetic fake leather but regardless like i said very comfortable it should be pretty easy to clean as well and i'll talk more about replacing the ear cups later on in the video now the last thing with regards to working like i said i'm always on phone calls all the time whether that's zoom calls for meetings or just actual regular phone calls so let's get into a microphone test in several different environments so starting off with the microphone test indoors you can see it does a pretty decent job and now this is the microphone with a lot of traffic behind me it's also pretty breezy out here but once again this microphone does a pretty decent job that's my summary of when i was wearing these while working let's talk about when you're relaxing listening to music watching movies whatever it is these are going to be great for that but there are a couple things that you want to be aware of starting off with what i liked about these of course the audio quality is a huge positive listening to music is very pleasant with these amazing soundstage great detail really analytical and as far as bluetooth wireless headphones go i mean these are are really among the best out there fantastic bitrate as well using ldac which is sony's codec with a substantially higher bit rate than most other audio uh most other codecs out there now if you prioritize a wired connection instead of wireless whether that is for latency reasons or just the ease of connection whatever it might be then you can first of all connect this by three and a half millimeter jack as you see right there and it comes with one in the in the case which i think is really convenient and so that's going to be great if you're just hanging out playing games on your laptop or watching netflix or whatever it might be but if you're going to use a desktop you're probably going to want to buy a longer cable can't knock sony for that one it makes perfect sense the size of cable they gave us and a big positive here is that when the headphones are off you can still play music through these using the jack but one kind of drawback kind of related to that and i'm not sure why sony still does this you're not able to have any kind of playback through usb type-c cables unlike a lot of other headphones like the sennheiser momentum threes for example where i can play music from my laptop or my desktop simply by plugging it in with a usb type-c cable now the benefit there is that you can have anc or transparency on without ever killing your battery in fact they're charging these while you're listening to music while you're using your microphone while you're using anc whatever it is the battery is obviously never going to die if you plug in like that so again i wish sony would do that especially at this price but and of course when you're just relaxing i already said sound quality is great comfort is fantastic latency is really not that bad with these i mean they're going to be perfect for a lot of things anything i talk about here is kind of i mean borderline nitpicking but i want to point out things that maybe are not the best about these or things that i think i would like to see improved and the next one is really the app although i really love these headphones in almost all regards the app gives you what you need but i think it feels a little outdated i think sony needs to kind of adjust maybe the ability to customize your controls for one even though they're all in the right ear they're very easy to remember there are things like for example the anc button you can customize that and you can double press it or triple press it but in both situations they only give you one option and it's the same option for both so if you double press you can open spotify and if you triple press you could open spotify i think that's kind of a wasted feature there sony really should be adding more to that but regardless it is what it is and like i said the controls at least on the ear cup the touch controls super intuitive swiping up and down for volume right and left for forward and back song double tapping to play pause i don't know can't get much better than that and another benefit is they're only on the right ear cups you never have to remember right versus left which ones play which one's pause so convenient and of course if you've seen any of the reviews when it first came out you probably know these are also really easy to pair from nfc pairing just tapping your phone on there or google fast pair as well like as soon as you turn them on it pops up on an android device and of course they come with no plastic or plastic free packaging again great initiative for the for the environment i'm happy sony's doing that so i work all day i hang out for a little bit in the evening and i i know you really shouldn't do this before you go to bed but i always work out like way too late i'll start a workout like 10 or 11 p.m and just lift for a while and then and then shower and go to bed not good i know but if you want to wear these headphones when you're working out this is something that i could have picture a lot of people doing you spend a lot of money on a good pair of headphones and although they're not specifically marketed to working out or to a kind of a fitness crowd they're still going to be a pretty solid pair there are a couple things you want to be aware of so starting off with the positives they fit really well like i said much more secure than the bose headphones in my opinion so if you look at workouts in like three different levels of like head movement the first one being squatting and benching and things like that i've done that these absolutely pass the test super easy they never fall off then level two would be like a run so going on run with these as long as your ears don't or your head doesn't get really sweaty they definitely stay on so if it's a little cooler out they're gonna be perfect in fact in the winter they'll even keep your ears warm but in the the heat of the summer i don't know if he's gonna be the best and i'll explain why in just a second but regardless they passed level two level three would be something like burpees and again i've done burpees with these on and they don't fall off my head which i was really really impressed with considering how comfortable and light they feel they don't feel like they're clamping your head and yet they're still on really securely but there is a caveat when it comes to working out one reason that these are not going to be ideal and that's why i said you don't want to wear these when it's hot out and and you know if you're going for a run that's because they don't actually have a water resistance rating so they tell you that you probably shouldn't wear these if it's raining outside or drizzling or if you're really sweaty because you could potentially damage the headphones now that doesn't mean that you definitely will just from being a little sweaty but it's something that maybe you don't want to risk and if you wear these when you're working out i mean i recommend cleaning them after every workout but eventually you're still going to want to be hygienic and replace the ear cups you know if they you know they might get a little smelly who knows but replacing the ear cups the positive here is that they're very easy to replace and they're relatively affordable you can find them on amazon for maybe 15 or 20 dollars and like i said you just pop them out it just snapped in place so a little screwdriver along the edge will just pop the snaps right off and you're ready to go and not to talk about sound quality too much again but when you're working out you want something that's loud and you want something with a lot of bass capabilities or at least i do and these really check the boxes there and make it very easy to get in the zone and work out and the last thing i want to talk about with working out is the gestures are very simple which makes it great for if you're doing if you're on a run you're working out or whatever it might be and you want to skip your song you just swipe forward it's super easy you don't have to worry about finding a small button and double pressing it or triple pressing it or anything like that now the last category i want to talk about is traveling or commuting so whether you're on a big trip across the country and you're flying or if you're just on a bus going into the city there are some pros and some cons here the first con is that as far as portability goes these are not great like they're pretty durable and all but the case is just it's large it doesn't let these fold down like the old model did and so that's a definitely a big negative there but regardless of the case size these are still my favorite headphones for traveling for a couple reasons one like i said the battery seems to last forever i can easily use these for 25 30 hours and they never die on me and the second thing probably the biggest one is the active noise cancellation these in my opinion are the best amc headphones on the market right now and i know this is something that a lot of people debate and there's different there's a lot more layers to ansi than people realize it's not just the raw power of the anc but rather how much white noise there is how clean it is and what frequencies are really blocked out and i think these do a great job of not just blocking out the frequencies with the active noise cancellation which are generally the lower frequencies but they also have some slightly better passive noise blocking than the previous model so these are going to block out higher sounds as well from crowds to voices to whatever it might be it really does a great job blocking pretty much everything out there and when you're traveling in public of course you want something that looks good in my opinion these are a little bit more stylish than the x mark fours which were a little bit bland these i think look a little better and a huge travel feature these have if you're on a bus or a train and you want to hear your stop is actually the palm like the cupping feature so if you just go like this and hold your hand there it'll go into a transparency mode you can hear your surroundings so if you hear like the train conductor starts saying something you could just go like this listen to what they're saying and then take your hand away and just goes right back to anc playing your music loud and you don't hear anything around you of course you could always just take your headphones off but cool feature so that's been it that's my take on the sony wh-1000 mark fives arguably the best bluetooth headphones on the market or at least my favorite and like i said there's really only a few things i wish these had i wish they folded up i wish they had an ip water resistance rating and i wish they were able to play music through usb type c but other than that really a fantastic pair of headphones leave a comment below and let me know what your experience has been like if you've been using these headphones anything good or bad i want to see in the comments below thanks for watching i'll see you next time [Music]"

# ALL IN ONE PLACE
1. `search_product`
2. `get some basic infos`
3. `get comments`
4. `get trnascripts`

In [19]:
query = "Sony WH-1000XM5 review"

videos = search_videos(query, max_no_results=5)

for video in videos:

    print("\n" + "=" * 70)

    print("TITLE:", video["title"])
    print("CHANNEL:", video["channel"])
    print("VIDEO ID:", video["video_id"])

    # Get statistics
    stats = get_video_stats(video["video_id"])

    print("\nSTATS:")
    print("Views:", stats["views"])
    print("Likes:", stats["likes"])
    print("Comments:", stats["comment_count"])

    # Get comments
    comments = get_top_comments(
        video["video_id"],
        max_results=10
    )

    print("\nTOP COMMENTS:")

    for comment in comments:
        print(
            f'{comment["likes"]} likes - '
            f'{comment["author"]}: '
            f'{comment["text"]}'
        )

    # Get transcript
    transcript = get_transcript(video["video_id"])

    print("\nTRANSCRIPT:")

    if transcript:
        print(transcript[:2000])
    else:
        print("Transcript unavailable")

======================================================================
TITLE: Sony WH 1000XM5 Review - Audiophile Perspective | The Best ANC Headphones?
CHANNEL: Trakin Tech English
VIDEO ID: aWWHU8-5oqU

STATS:
Views: 50651
Likes: 1355
Comments: 109

TOP COMMENTS:
1 likes - @tgfan972: waiting for video on "best over/on ear Headphones in every budget "
1 likes - @shilpasankpal7350: Yes I recently purchased it
It’s voice cancellation feature is amazing . Adaptive voice cancellation is very useful . Comfort of headphones is amazing . I got it for 26k from I world shop
0 likes - @ashunegi6216: bro iam convinced that you have great music taste you listening to TOOL's undertow sober is mind blowing
3 likes - @vasqora: Can you do a over the ear headphone list for under 10k for beginner audiophiles. i basically needed something with a mic and above average audio quality. i checked out reviews for some gaming headphones as well but cant bring my self to trust them, wireless would be appreciated.
3 likes - @abhijitbagchi3471: Please make a playlist, your song recommendations are really good.
1 likes - @NOTFATEEN: For me comfort is not the main selling point it's the audio quality which matters and sony never concentrated on that at all
0 likes - @arjunmohandas8870: Sony tunes it for mass market and not audiophiles, they can easily make a neutral sounding one but no issues, you have a fantastic sound stage and EQ options. So these are wonderful. Kudos Sony
0 likes - @AjaykrishAJ: Kindly share the EQ system clearly in the sony app, It will help many❤
1 likes - @TejaSaiTipirisetty: The audio you guys recorded sounded so robot like… what changes did you make to your setup and editing?
0 likes - @surajsukne1705: Just lost carring case for my xm5, any suggestions where i can get new one ?

TRANSCRIPT:
so Sony's wh 1000xm series is generally their Flagship lineup of you know active noise cancellation headphones and this one is the Sony wh 1000xm5 the latest in their land and you know Flagship active noise cancellation headphones are second only to truly wireless earbuds in terms of popularity these things do sell out really fast so last year when Sony introduced the wh 000xm4 that was a very minimal upgrade over the you know preceding WS thousand xm3 the naming scheme is really terrible so I'm going to be calling it xm4 and xm3 going forward anyway the xm5 itself is kind of a substantial upgrade over the xm4 and let's talk about that in this review if you don't know me yet my name is Asha you're watching track into English let's review the Sony w8000xm5 the first immediate change that you will notice is of course the design of these headphones the aesthetic is far more minimal and modern looking in nature and looks better than the preceding WS thousand xm4 however there are some functionalities you'd lose out as a result of the new design so firstly it only folds flat so it cannot fold up entirely like you could on the witch thousand xm4 which means that the case now is much much bigger as well it's a nice case no doubt but it doesn't fit in my slim backpack that easily there's another fundamental problem of the design and it is when you're not listening to music and you wear your headphones around your neck they don't close up entirely like this they don't swivel completely flat which means that if you want them sitting flat around your neck you will have to change the orientation and that's kind of odd because when you're going to listen to music again you'll have to do this so it's not very intuitive in nature also one more thing I noticed is that the accessories that are bundled with these include that type A to type c adapter for charging of course and the 3 0.5 mm extension you know cable for when you want to listen in wired mode but there is no airplane ada

======================================================================
TITLE: Sony WH-1000XM5 Review: Two Steps Forward, One Step Back!
CHANNEL: Marques Brownlee
VIDEO ID: 6CsJZxfZsL0

STATS:
Views: 6509941
Likes: 189589
Comments: 7554

TOP COMMENTS:
152 likes - @HelloJoseph83: Just got these for $200 on Prime Day. Just had to wait 4 years.
15588 likes - @arjunsankar: The sound design in this video is absolutely beautiful. I hope this trend continues in your future headphone review videos.
6638 likes - @LLANTALOBOTOMIK: I actually love the fact that they won't fold. Folding make them weaker and they rattle a lot.
5099 likes - @RaedVS: I think not being foldable will eventually be better for durability in the long term
382 likes - @birkpaulsen: My Sony WH-1000XM4 don’t jiggle jiggle, it folds
78 likes - @someonebartender: I hate how marques makes you like the product But at the same time he makes you hate it.
1164 likes - @vidIQ: Alternative Title - Sony WH-1000XM5 Review: Four Microphones Forward, Two Folds Back!
3 likes - @gibrankhaliq: Here in 2026, literally listening to these on new WH-1000XM5's appreciating how good the soundstage on this video is. Wish me luck with them hinges peeps! Please and thank you.
6184 likes - @TheGroovyGuitarDude: I’m still rocking the Mark 3s and love them, not enough improvement to justify upgrading yet! 🎧
30 likes - @Neoxon619: Wow, I didn’t realize how long it’s been since the XM4s dropped.

TRANSCRIPT:
[Music] hey what's up mbhd here okay so for the past few years Sony's Flagship noise cancelling headphones have been the King of the Hill of course they've made some minor adjustments and feature additions over the past few so by the time they got to The Mark iiiii with their comfort and noise cancelling and USB type-c they were the top of the market and then the markv added Multi-Device support but they've essentially looked the same sounded excellent and they've been an easy recommendation as a result but these new Mark 5 on the other hand are a real departure from that formula a lot of the changes I do really like but there is one big one that I definitely don't so the first thing you might be wondering is is there actually a sound Improvement but I actually want to just start with the new design cuz you can see that they have this new shape that is this pretty minimal sharp and clean look there is still a dark and a light this light is a sort of a cream colored version and there's a lot of good things about this design the ear cups are slightly bigger and wider the new vegan leather material is so much softer it is it's kind of amazing it combines that with the super lightweight of the whole headphones to make this entire pair more comfortable to wear for long periods of time honestly I'm just going to say this is the most comfortable pair of noise cancelling headphones I've ever tried you still have a touch sensitive panel on the right side ear cup for skipping pausing Etc they actually still have onoff head detection despite not having a plastic cutout in the ear cup like the last one and there's now twice as many many slots for microphones around the outside it goes from four total to four on each side eight total microphones and I'll get into what that does for noise cancellation and voice quality in a second but you can see they're fairly minimal and hidden well in this new design but overall overall I actually still feel like this design is a downgrade for

======================================================================
TITLE: Sony WH-1000XM5 Headphones Review - 6 Months Later
CHANNEL: 6 Months Later
VIDEO ID: dEHYA-jACoU

STATS:
Views: 287639
Likes: 2746
Comments: 232

TOP COMMENTS:
12 likes - @jesuscervantesj82: Well i got mines in the blue and i love my babies they are fucken amazing the comfort has been amazing the noise canceling is stellar i can wear these for hours and still have no issues
245 likes - @jenna8832-n2g: I have these and the battery life and comfort is outstanding.  I have been seeking comfort in headphones for years and these are the best I've ever used.  I wore these for three hours straight and experienced no discomfort at all.  My ears are relatively small (as a female) so perhaps these are more perfect for me than the reviewer who has larger ears.  As for battery life, after charging them to 100% and using them for 6 hours, I have 80% of battery life left.
29 likes - @evilkidd1876: I just bought a pair.. and so far they're awesome. I dont care that they dont fold.. the sound quality and nc is s tier. The case is good as well. Theyre comfortable as. Lightweight..probably the most comfortable I've ever tried. They're retailed in JBHIFI@$700.00 but i purchased mine at PBTECH for $460.00 here in NZ.

I originally wanted the xm4 model but these were the only ones available. However.. no regrets. Happy purchase. I've owned all the Beats & most of the the other headphones available but these definitely are worth the buy.
12 likes - @paulz7716: You have not mentioned the missing sidetone feature which is so important for taking calls (where you actually hear your own voice while speaking with someone)
0 likes - @mNazarewicz: Thanks man! I have those headphones in my basket, but now I will try your other reviews first, and then eventually decide to buy XM5s.
5 likes - @thisismyname670: watching this video with the xm5 is amazing 😁🙌🏻
0 likes - @mario17-t34: what are the best sony  for comfort, Sony WH-1000XM6 ?? Is those ear room  bigger ?
0 likes - @kristianmorelos2553: so the transparency mode, is the sound distorted?  I like the design.
0 likes - @Jesusandbible: to me a volime booster is what makes headphones better, can these volume boost? Thanks!
0 likes - @Joaquinhos: Whats a good headphone set with more space in the cups? Anyone tried the Audio Technica set -M60XBT i believe it was called? Or have other tips? Would appreciate it-

TRANSCRIPT:
The Sony WH-1000XM5 Wireless Noise Canceling
headphones are considered one of the best   over-the-ear headphones you can get nowadays
and for good reason, they’re well-designed,   have great battery life and a good sound.
But after six months of using them, I don't   think they're the perfect set of headphones
for everyone out there, myself included. And I'll take you through why that is
as well as who I think should pick up   a pair. But first let's talk about the
good stuff and first up is battery life,   they’re rated for 30 hours of playback with
noise cancellation on and in my experience,   their battery life has been excellent
as well as their standby battery. Noise Cancellation is the next thing I really
like about these headphones. As you’d come to   expect from Sony, they’re excellent, and
comparable to my pair of AirPods Max,   another pair of noise canceling earbuds
I absolutely love And if you want to hear   how I think these headphones compare
against each other, I'll link to the   comparison video i did of both of them here
in this video and in the description below. Another thing I like about the Sony XM5s is
Sony’s headphones app, minus the weird badge   tab. The app is available for both Android and iOS
lets you customize the level of noise cancellation   you experience as well as the EQ. Those are
the two things I've mainly used it for and   the noise cancelation is great in a variety of
situations from working in a crowded office to   being on an airplane and Sony’s is one of the
best, it cancels out pretty much everything. Next up sound. Now, while I don't think these
headphones are the absolute best sounding pair   of headphones i've ever used, Sony did include two
features on them that really does help you find   the way they sound. And these features are the
equalizer and LDAC support. LDAC is a proprietary   Sony codec that allows you to stream higher
quality music over Bluetooth and is supported by   devices like many A

======================================================================
TITLE: Sony WH-1000XM5 Review - Taylor Swift Sounds Good in These
CHANNEL: Ryan Kennedy
VIDEO ID: qnEKEI4ZoHo

STATS:
Views: 4788905
Likes: 167185
Comments: 1596

TOP COMMENTS:
281 likes - @realryankennedy: Become part of the Savvy Fam: https://ezbiolink.com/thesavvyfam
29778 likes - @Gpinky765: Wow the sound quality sounds just like my phone speakers
4837 likes - @hololivevirus4854: "You'll be in luck if you have headphone on"

*Ah finally I can hear premium quality with my $5 headphone*
8681 likes - @zorsenothorse: Me listening with headphones: wow they sound the same as my headphones!
891 likes - @Rainsanker: "Listen to the sound quality"
*plays fart sounds*
1840 likes - @chunLi29: When he just stares at you, I could feel the gaze from my soul 😂😂😂😂
45 likes - @stormrunnercore: Over here still using my ancient XM2’s. 7 years later and still so happy with them.
5710 likes - @rileyzxr: wow, thx for letting me try it man.
9 likes - @zacharymoerder1795: Of course I have headphones on... you're holding them there for me
462 likes - @mralxndr2846: At first I thought it was a cooking pan from the picture on the package xD

TRANSCRIPT:
why do a lot of people say that these are some of the best headphones in their price category and even above i've just gotten a package today let's unpack it and take a look at it let's first take a look and see if these are comfortable the cushion's very soft i've got a type c port on one end and a mini audio on the other there's only two buttons on this beauty the power button and this one here the usb and the mini audio are conveniently stored in this compartment the folding mechanism is very interesting for this price it's actually off center so when you open the headphones and ready to listen they create the right amount of tension and take your head shape the adjusting mechanism is very smooth has got no clicks and has the right amount of tension now i'll give you a chance to listen to the sound quality you'll be in luck if you have headphones on you

======================================================================
TITLE: Sony WH-1000XM5 Two-Years Later Review: Still Worth BUYING?
CHANNEL: SoundGuys
VIDEO ID: vMi6olkSj7g

STATS:
Views: 128580
Likes: 1451
Comments: 196

TOP COMMENTS:
1 likes - @SoundGuys: Buy At Amazon: https://soundg.co/r1g0ox

Read our full-review: https://www.soundguys.com/sony-wh-1000xm5-review-71783/

[Affiliate Disclosure: As an Amazon Associate we earn from qualifying purchases.]
23 likes - @GauBan2501: I got these for "free" when I pre-ordered my Xperia 1V  in 2023. I still use them for almost everything around the house. I've had a true OG audio nut try them. He was really impressed.
6 likes - @Btree33: These have the best noise cancelling because they don’t give you that weird pressure
11 likes - @daknaf12: The problem with Snapdragon Sound/AptX Lossless is that no major phone in the US supports it. It's not on Galaxy, iPhone, or Pixel. LDAC is the best option for most US Android users bc it's on both Pixel and Galaxy.
0 likes - @areena_shrestha: I was looking for this ! Thanks Harley 😂🔥
23 likes - @Air-d3z: I just bought these, and yes I tried every other options.

The Airpods Max, well let just say you’re mostly buying for its build quality and that premium feel (and that Apple thing).

Beats Studio Pro, sounds decent but portability is not that good and not the most comfortable.


Sonos, if you like a lookalike AirPods Max but with better sound.


Bose, that’s the close one and the one I should’ve bought for its specs for just a couple more bucks.

But here I am with the XM5s and it’s just right. It’s not the most latest or has new features and that’s fine.
0 likes - @howellcp: I’m still rocking the MX2s and they are great.
8 likes - @DarianSilva-n4h: Bro this vid saved me so much time, thank you so much 😭
2 likes - @daknaf12: The problem with AptX Adaptive is that no major phone in the US supports it. It's not on Galaxy, iPhone, or Pixel.
1 likes - @alextanguay5886: Just tried these earlier at Best Buy..the lightest over ear headphones on the market.  I’m deciding between these and the ear buds

TRANSCRIPT:
look I consider the Sony wh1000 xm5 the Thanos of noise cancelling headphones why you ask well because if you try to go on Google or YouTube and look up the best noise cancelling headphones pretty much all websites will mention these it's inevitable but 2 years after the release of these headphones there have been plenty of additions to the market and that makes me wonder are the xm5 headphones still the best overall headphones around or should you look towards newer models from other brands now to make it easy I'm going to start by talking about four reasons why the xm5 headphones are still considered the King of erss and at the end I'll also discuss one big reason why the xm5 headphones may not be the right choice for you and this could actually impact your own listening experience so make sure to stay tuned for that all right let's start with the good first off Sony did an excellent job with the build quality and it still holds up to today's standards now sure it doesn't feel as durable as its thicker looking predecessor but the thinner headband here and the Hollow construction makes the headphones feel really light on the head and I have no problems wearing the headphones for hours on end I'd like in the comfort of the xm5 headphones to something like the Bose Qui Comfort 45 which I still consider to be the most comfortable headphones I've ever worn the ear pads also feel very plush and the ear Cup itself is deeper than the ear cup on the xm4 so if you have larger ears or you just have a bigger head I'd highly recommend getting the XM 5S instead of the xm4 even if if it will cost you a little extra secondly these headphones still have great software support via the Sony headphones Connect app inside the app you get access to a ton of useful features like The Equalizer which can be used for fine-tuning the sound to your liking Ambient sound controls adaptive sound controls for adjusting the ANC and Ambient sound depending on what you're doing and you can also use